# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['https://idpay.ir/mhkarami97','https://www.blockchain.com/btc/address/bc1qew7qavv6rwat6nwljunncaz0skcj2929vlv950','https://etherscan.io/address/0x3E69d4DAefF75eA21Eb72B65a1DEE841B71Ac633','https://explorer.cardano.org/en/address?address=addr1q8l534pwa5qkq20v3mdk9ddvp2qkvumszc8j82ut2fwenc0lfr2zamgpvq57erkmv266cz5pveehq9s0yw4ck5jan8ssqav7dm']

